model:
  num_classes: 2
  cnnrnn:
    rnn_hidden_size: 256
    rnn_num_layers: 1

training:
  batch_size: 8
  lr: 0.0001
  epoch: 20


dataset:
  data_dir: /nfs/users/sohel/shot-classification-frames #"/nfs/users/sohel/cricket_shot_dataset"
  # ann_dir: "/nfs/users/sohel/cricket_shot_dataset/classification_labels.csv"